export const GET_COURSE_CATALOG = 'GET_COURSE_CATALOG';
export const GET_COURSE_LIST = 'GET_COURSE_LIST';
export const SET_KEYCATALOG = 'SET_KEYCATALOG';
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL';
